;; in this problem, we only have dollar at the bank. we would have to visit changeOffice multiple times to 
;; obtain euro and sterling
(define (problem nightout)
 (:domain nightout)
 
 (:objects pub supermarket home shop eiffel - location
           bank1 bank2 bank3 bank4 bank5 - location
           changeOffice - location
           dollar sterling euro - currency)
 
 (:init (at  home)
        (canbuy supermarket dollar)
        (canbuyshoes shop dollar)
        (canexchange changeOffice dollar sterling)
        (canexchange changeOffice sterling dollar)
        (canexchange changeOffice dollar euro)
        (canexchange changeOffice euro dollar)
        (canexchange changeOffice euro sterling)
        (canexchange changeOffice sterling euro)
        (visit eiffel)
        (canwithdraw_pound bank1)
        (canwithdraw_pound bank2)
        (canwithdraw_dollar bank3)
        (canwithdraw_dollar bank4)
        (canwithdraw_euro bank5)
 		(available)
        
        
        (= (maxwithdraw bank1 sterling) 150)
        (= (maxwithdraw bank2 sterling) 150)
        (= (maxwithdraw bank3 dollar) 150)
        (= (maxwithdraw bank4 dollar) 150)
        (= (maxwithdraw bank5 euro) 400)
        (= (exchangeRate dollar sterling) 0.71)
        (= (exchangeRate sterling dollar) 1.41)
        (= (exchangeRate dollar euro) 0.88)
        (= (exchangeRate euro dollar) 1.14)
        (= (exchangeRate sterling euro) 1.24)
        (= (exchangeRate euro sterling) 0.81)
      
        (= (inpocket dollar) 2)
        (= (inpocket sterling) 2)
        (= (inpocket euro) 2)
                 (link bank1 bank2)
    (link bank2 bank1)
    (link bank1 bank3)
    (link bank3 bank1)
    (link bank1 bank4)
    (link bank4 bank1)
    (link bank2 bank3)
    (link bank3 bank2)
    (link bank2 bank4)
    (link bank4 bank2)
    (link bank3 bank4)
    (link bank4 bank3)
    
    (link bank1 bank5)
    (link bank5 bank1)
    (link bank2 bank5)
    (link bank5 bank2)
    (link bank4 bank5)
    (link bank5 bank4)
    (link bank3 bank5)
    (link bank5 bank3)

    (link Home bank1)
    (link bank1 Home)
    (link Home bank2)
    (link bank2 Home)
    (link Home bank3)
    (link bank3 Home)
    (link Home bank4)
    (link bank4 Home)
        (link Home bank5)
    (link bank5 Home)

    (link Home pub)
    (link pub Home)
    (link Home supermarket)
    (link supermarket Home)
    (link Home shop)
    (link shop Home)
        (link Home changeOffice)
    (link changeOffice Home)

        (link eiffel bank1)
    (link bank1 eiffel)
    (link eiffel bank2)
    (link bank2 eiffel)
    (link eiffel bank3)
    (link bank3 eiffel)
    (link eiffel bank4)
    (link bank4 eiffel)
        (link eiffel bank5)
    (link bank5 eiffel)

    (link eiffel pub)
    (link pub eiffel)
    (link eiffel supermarket)
    (link supermarket eiffel)
    (link eiffel shop)
    (link shop eiffel)
    (link eiffel changeOffice)
    (link changeOffice eiffel)

    (link pub bank1)
    (link bank1 pub)
    (link pub bank2)
    (link bank2 pub)
    (link pub bank3)
    (link bank3 pub)
    (link pub bank4)
    (link bank4 pub)
    (link pub bank5)
    (link bank5 pub)
    
    
    (link supermarket bank1)
    (link bank1 supermarket)
    (link supermarket bank2)
    (link bank2 supermarket)
    (link supermarket bank3)
    (link bank3 supermarket)
    (link supermarket bank4)
    (link bank4 supermarket)
     (link supermarket bank5)
    (link bank5 supermarket)   
    
    (link shop bank1)
    (link bank1 shop)
    (link shop bank2)
    (link bank2 shop)
    (link shop bank3)
    (link bank3 shop)
    (link shop bank4)
    (link bank4 shop)
    (link shop bank5)
    (link bank5 shop)

        (link changeOffice bank1)
    (link bank1 changeOffice)
    (link changeOffice bank2)
    (link bank2 changeOffice)
    (link changeOffice bank3)
    (link bank3 changeOffice)
    (link changeOffice bank4)
    (link bank4 changeOffice)
     (link changeOffice bank5)
    (link bank5 changeOffice)   
 )
		
 (:goal (and (have_enough dollar) (have_enough sterling) (have_enough euro) (gotsnacks) (gotshoes) (at pub) (visited eiffel) ) )
) 