;; in this problem, we decrease the available sterling at the banks, so that the planner gets to exchange dollar to sterling.. 
(define (problem nightout)
 (:domain nightout)
 
 (:objects pub supermarket home shop eiffel - location
           bank1 bank2 bank3 bank4 - location
           changeOffice - location
           dollar sterling - currency)
 
 (:init (at  home)
        (canbuy supermarket dollar)
        (canbuyshoes shop dollar)
        (canexchange changeOffice dollar sterling)
        (canexchange changeOffice sterling dollar)
        (visit eiffel)
        (canwithdraw_pound bank1)
        (canwithdraw_pound bank2)
        (canwithdraw_dollar bank3)
        (canwithdraw_dollar bank4)
 		(available)
        
        
        (= (maxwithdraw bank1 sterling) 5)
        (= (maxwithdraw bank2 sterling) 5)
        (= (maxwithdraw bank3 dollar) 600)
        (= (maxwithdraw bank4 dollar) 600)
        (= (exchangeRate dollar sterling) 0.71)
        (= (exchangeRate sterling dollar) 1.41)
      
        (= (inpocket dollar) 2)
        (= (inpocket sterling) 2)
                 (link bank1 bank2)
    (link bank2 bank1)
    (link bank1 bank3)
    (link bank3 bank1)
    (link bank1 bank4)
    (link bank4 bank1)
    (link bank2 bank3)
    (link bank3 bank2)
    (link bank2 bank4)
    (link bank4 bank2)
    (link bank3 bank4)
    (link bank4 bank3)

    (link Home bank1)
    (link bank1 Home)
    (link Home bank2)
    (link bank2 Home)
    (link Home bank3)
    (link bank3 Home)
    (link Home bank4)
    (link bank4 Home)

    (link Home pub)
    (link pub Home)
    (link Home supermarket)
    (link supermarket Home)
    (link Home shop)
    (link shop Home)
        (link Home changeOffice)
    (link changeOffice Home)

        (link eiffel bank1)
    (link bank1 eiffel)
    (link eiffel bank2)
    (link bank2 eiffel)
    (link eiffel bank3)
    (link bank3 eiffel)
    (link eiffel bank4)
    (link bank4 eiffel)

    (link eiffel pub)
    (link pub eiffel)
    (link eiffel supermarket)
    (link supermarket eiffel)
    (link eiffel shop)
    (link shop eiffel)
    (link eiffel changeOffice)
    (link changeOffice eiffel)

    (link pub bank1)
    (link bank1 pub)
    (link pub bank2)
    (link bank2 pub)
    (link pub bank3)
    (link bank3 pub)
    (link pub bank4)
    (link bank4 pub)
    
    (link supermarket bank1)
    (link bank1 supermarket)
    (link supermarket bank2)
    (link bank2 supermarket)
    (link supermarket bank3)
    (link bank3 supermarket)
    (link supermarket bank4)
    (link bank4 supermarket)
    
    
    (link shop bank1)
    (link bank1 shop)
    (link shop bank2)
    (link bank2 shop)
    (link shop bank3)
    (link bank3 shop)
    (link shop bank4)
    (link bank4 shop)

        (link changeOffice bank1)
    (link bank1 changeOffice)
    (link changeOffice bank2)
    (link bank2 changeOffice)
    (link changeOffice bank3)
    (link bank3 changeOffice)
    (link changeOffice bank4)
    (link bank4 changeOffice)
    
 )
		
 (:goal (and (have_enough dollar) (have_enough sterling) (gotsnacks) (gotshoes) (at pub) (visited eiffel) ) )
) 